# Generated by Django 3.2 on 2022-09-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceUsedNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机名')),
                ('host_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='硬件ID')),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('int_total', models.IntegerField(blank=True, null=True, verbose_name='总接口数')),
                ('int_used', models.IntegerField(blank=True, null=True, verbose_name='已使用')),
                ('int_unused', models.IntegerField(blank=True, null=True, verbose_name='未使用')),
                ('utilization', models.FloatField(blank=True, null=True, verbose_name='使用率')),
                ('int_used_1g', models.IntegerField(blank=True, null=True, verbose_name='1G接口使用')),
                ('int_used_10m', models.IntegerField(blank=True, null=True, verbose_name='10M接口使用')),
                ('int_used_100m', models.IntegerField(blank=True, null=True, verbose_name='100M接口使用')),
                ('int_used_10g', models.IntegerField(blank=True, null=True, verbose_name='10G接口使用')),
                ('int_used_20g', models.IntegerField(blank=True, null=True, verbose_name='20G接口使用')),
                ('int_used_25g', models.IntegerField(blank=True, null=True, verbose_name='25G接口使用')),
                ('int_used_40g', models.IntegerField(blank=True, null=True, verbose_name='40G接口使用')),
                ('int_used_100g', models.IntegerField(blank=True, null=True, verbose_name='100G接口使用')),
                ('int_used_irf', models.IntegerField(blank=True, null=True, verbose_name='堆叠接口使用')),
                ('int_used_auto', models.IntegerField(blank=True, null=True, verbose_name='auto接口使用')),
                ('int_unused_1g', models.IntegerField(blank=True, null=True, verbose_name='1G接口未使用')),
                ('int_unused_10m', models.IntegerField(blank=True, null=True, verbose_name='10M接口未使用')),
                ('int_unused_100m', models.IntegerField(blank=True, null=True, verbose_name='100M接口未使用')),
                ('int_unused_10g', models.IntegerField(blank=True, null=True, verbose_name='10G接口未使用')),
                ('int_unused_20g', models.IntegerField(blank=True, null=True, verbose_name='20G接口未使用')),
                ('int_unused_25g', models.IntegerField(blank=True, null=True, verbose_name='25G接口未使用')),
                ('int_unused_40g', models.IntegerField(blank=True, null=True, verbose_name='40G接口未使用')),
                ('int_unused_100g', models.IntegerField(blank=True, null=True, verbose_name='100G接口未使用')),
                ('int_unused_irf', models.IntegerField(blank=True, null=True, verbose_name='堆叠接口未使用')),
                ('int_unused_auto', models.IntegerField(blank=True, null=True, verbose_name='auto接口未使用')),
                ('log_time', models.DateTimeField(blank=True, null=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': '接口利用率表',
                'db_table': 'interface_used_new',
            },
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['host'], name='interface_u_host_effadc_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['host_id'], name='interface_u_host_id_c4d879_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['host_ip'], name='interface_u_host_ip_28ca6c_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_total'], name='interface_u_int_tot_74cd00_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used'], name='interface_u_int_use_bc6019_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused'], name='interface_u_int_unu_7845a5_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['utilization'], name='interface_u_utiliza_fe0cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_1g'], name='interface_u_int_use_e18b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_10m'], name='interface_u_int_use_d35b16_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_100m'], name='interface_u_int_use_d7cbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_10g'], name='interface_u_int_use_0d738e_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_20g'], name='interface_u_int_use_dec340_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_25g'], name='interface_u_int_use_c9bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_40g'], name='interface_u_int_use_8b2ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_100g'], name='interface_u_int_use_aec384_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_irf'], name='interface_u_int_use_b048db_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_used_auto'], name='interface_u_int_use_d45356_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_1g'], name='interface_u_int_unu_58e6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_10m'], name='interface_u_int_unu_25c2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_100m'], name='interface_u_int_unu_bb5a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_10g'], name='interface_u_int_unu_3df481_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_20g'], name='interface_u_int_unu_9c5546_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_25g'], name='interface_u_int_unu_ef4a83_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_40g'], name='interface_u_int_unu_1566ef_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_100g'], name='interface_u_int_unu_8f4a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_irf'], name='interface_u_int_unu_4cd571_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['int_unused_auto'], name='interface_u_int_unu_e1d96b_idx'),
        ),
        migrations.AddIndex(
            model_name='interfaceusednew',
            index=models.Index(fields=['log_time'], name='interface_u_log_tim_3700a6_idx'),
        ),
    ]
