# Generated by Django 3.2.15 on 2023-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_utilization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceusednew',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='主机名'),
        ),
    ]
