# Generated by Django 3.2.17 on 2023-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_utilization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceusednew',
            name='int_unused_200g',
            field=models.IntegerField(blank=True, null=True, verbose_name='200G接口未使用'),
        ),
        migrations.AddField(
            model_name='interfaceusednew',
            name='int_unused_400g',
            field=models.IntegerField(blank=True, null=True, verbose_name='400G接口未使用'),
        ),
        migrations.AddField(
            model_name='interfaceusednew',
            name='int_used_200g',
            field=models.IntegerField(blank=True, null=True, verbose_name='200G接口使用'),
        ),
        migrations.AddField(
            model_name='interfaceusednew',
            name='int_used_400g',
            field=models.IntegerField(blank=True, null=True, verbose_name='400G接口使用'),
        ),
    ]
