version: "3.2"
networks:
  docker_netaxe:
    external: true
services:
  regiscenter:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/regiscenter:2.3
    container_name: regiscenter
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - 31468:4168
    networks:
      - docker_netaxe
    restart: always

  prometheus:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/prometheus:v1
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_web.yml:/prometheus/web.yml
      - ./prometheus-data:/prometheus
      - net=host
    command: ['--web.enable-lifecycle','--web.config.file=/prometheus/web.yml','--storage.tsdb.retention.time=30d', '--config.file=/etc/prometheus/prometheus.yml']
    ports:
      - 39090:9090
    networks:
      - docker_netaxe

  blackbox_exporter:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/blackbox-exporter:master
    container_name: blackbox_exporter
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./blackbox.yml:/config/blackbox.yml
    ports:
      - 9115:9115
    networks:
      - docker_netaxe

