global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: '默认节点'

scrape_configs:
  - job_name: 'icmp_connect_15s'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [ icmp ]
    http_sd_configs:
      - url: http://SERVER_IP:31468/regis/services
        basic_auth:
          username: admin
          password: REGIS_PASSWORD
    relabel_configs:
      - source_labels: [ '__address__' ]
        target_label: __param_target
      - source_labels: [ '__address__' ]
        target_label: instance
      - target_label: __address__
        replacement: SERVER_IP:9115
      - source_labels: [ env ]
        regex: .*icmp_15s.*
        action: keep
  - job_name: 'tcp_connect_15s'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [tcp_connect]
    http_sd_configs:
      - url: http://SERVER_IP:31468/regis/services
        basic_auth:
          username: admin
          password: REGIS_PASSWORD
    relabel_configs:
      - source_labels: ['__address__','port']
        target_label: __param_target
        regex: "(.*);(.*)"
        replacement: "$1:$2"
        action: replace
      - source_labels: ['__address__','port']
        target_label: instance
        regex: "(.*);(.*)"
        replacement: "$1:$2"
        action: replace
      - target_label: __address__
        replacement: SERVER_IP:9115
      - source_labels: [env]
        regex: .*tcp_connect_15s.*
        action: keep
  - job_name: 'tcp_connect_all'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [tcp_connect]
    http_sd_configs:
      - url: http://SERVER_IP:31468/regis/services
        basic_auth:
          username: admin
          password: REGIS_PASSWORD
    relabel_configs:
      - source_labels: ['__address__','port']
        target_label: __param_target
        regex: "(.*);(.*)"
        replacement: "$1:$2"
        action: replace
      - source_labels: ['__address__','port']
        target_label: instance
        regex: "(.*);(.*)"
        replacement: "$1:$2"
        action: replace
      - target_label: __address__
        replacement: SERVER_IP:9115
      - source_labels: [env]
        regex: .*tcp_connect_all.*
        action: keep
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['SERVER_IP:39090']
    basic_auth:
      username: admin
      password: REGIS_PASSWORD