# Generated by Django 3.2.17 on 2023-03-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单名')),
                ('menuUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='路径')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标样式')),
                ('parentPath', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='父路径')),
                ('badge', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='badge')),
                ('iconPrefix', models.CharField(blank=True, default='iconfont', max_length=100, null=True, verbose_name='图标样式')),
                ('showOrder', models.IntegerField(blank=True, null=True, verbose_name='排序序号')),
            ],
            options={
                'verbose_name_plural': '一级菜单',
                'db_table': 'navigation',
            },
        ),
        migrations.CreateModel(
            name='NavigationSubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单名')),
                ('menuUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='路径')),
                ('badge', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='badge')),
                ('showOrder', models.IntegerField(blank=True, null=True, verbose_name='排序序号')),
                ('cacheable', models.BooleanField(blank=True, default=False, verbose_name='是否缓存')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_profile', to='route_backend.navigationprofile', verbose_name='一级菜单')),
                ('subParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_on', to='route_backend.navigationsubprofile', verbose_name='子菜单')),
            ],
            options={
                'verbose_name_plural': '二级菜单',
                'db_table': 'navigation_sub',
            },
        ),
    ]
