version: "3.2"

networks:
  docker_netaxe:
    external: true

services:
    # 后端入口
    ipam-backend:
      container_name: ipam-backend
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-backend:1.0
      command: sh init.sh
      environment:
        TZ: Asia/Shanghai
      volumes:
        - /etc/localtime:/etc/localtime
        - ./config.json:/config/config.json
        - ./logs:/app/logs
      networks:
          - docker_netaxe
      restart: always

    # nginx代理
    ipam-nginx:
      container_name: ipam-nginx
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/ipam-nginx:1.23.1
      environment:
        TZ: Asia/Shanghai
      volumes:
        - /etc/localtime:/etc/localtime
      networks:
          - docker_netaxe
      ports:
          - "31103:80"

