version: "3.2"
networks:
  docker_netaxe:
    external: true
    
services:
  abac-backend:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/abac-backend:2.0
    container_name: abac-backend
    restart: always
    volumes:
      - ./config.json:/config/config.json
      - ./logs:/app/logs
    command: sh start.sh web
    networks:
      - docker_netaxe

  # nginx代理
  abac-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/abac-nginx:2.0
    container_name: abac-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker_netaxe
    ports:
      - "31104:80"

#  rbac-web:
#    image: registry.cn-hangzhou.aliyuncs.com/netaxe/rbac-web:1.0
#    container_name: rbac-web
#    restart: always
#    depends_on:
#      - rbac-backend
#    ports:
#      - "32204:80"
#    networks:
#      - docker_netaxe