# -*- coding: utf-8 -*-
server:
  mode: debug   # 可选值: debug, test, release
  port: 8000      # 可选端口号配置
  log_directory: /var/log

  network_device:
    url: "http://base-nginx:80/base_platform/asset/asset_networkdevice"
    api_secret: "X-API-KEY"
    limit: 6000
    polling_interval: 30m
    registration:
      addr: http://base-nginx:4168/regis/servers/
      username: admin
      password: zuVc0FUdd1sB
      target_server: network_monitor


mysqlconf:
  server: mysql-server
  port: 3306
  database: neteye
  username: root
  password: MYSQL_PASSWD

dbsource: