# Generated by Django 3.2.15 on 2022-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('Huawei', 'Huawei'), ('Cisco', 'Cisco')], default='H3C', max_length=50, verbose_name='厂商')),
                ('category', models.CharField(choices=[('switch', 'switch'), ('firewall', 'firewall'), ('router', 'router')], default='交换机', max_length=50, verbose_name='类型')),
                ('pattern', models.CharField(choices=[('match-compliance', 'match-compliance'), ('mismatch-compliance', 'mismatch-compliance')], default='match-compliance', max_length=50, verbose_name='模式')),
                ('regex', models.TextField(default='', verbose_name='表达式')),
                ('is_repair', models.BooleanField(default=False, verbose_name='是否修正')),
                ('repair_cmds', models.TextField(default='', verbose_name='修复命令')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '配置合规表',
                'verbose_name_plural': '配置合规表',
                'db_table': 'config_compliance',
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('CISCO', 'CISCO'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置项名称')),
                ('config_yaml', models.TextField(blank=True, default='', verbose_name='yaml内容')),
                ('config_jinja2', models.TextField(blank=True, default='', verbose_name='jinja2内容')),
                ('config_text', models.TextField(blank=True, default='', verbose_name='配置命令')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置片段表',
                'verbose_name_plural': '配置片段表',
                'db_table': 'config_template',
            },
        ),
        migrations.CreateModel(
            name='TTPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('CISCO', 'CISCO'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('ttp_content', models.TextField(blank=True, default='', verbose_name='模板内容')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置片段表',
                'verbose_name_plural': '配置片段表',
                'db_table': 'ttp_template',
            },
        ),
        migrations.AddIndex(
            model_name='ttptemplate',
            index=models.Index(fields=['name', 'vendor'], name='ttp_templat_name_1944b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ttptemplate',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddIndex(
            model_name='configtemplate',
            index=models.Index(fields=['name', 'vendor'], name='config_temp_name_09cec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configtemplate',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['vendor'], name='config_comp_vendor_292331_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['category'], name='config_comp_categor_4829f4_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['datetime'], name='config_comp_datetim_5e0126_idx'),
        ),
    ]
