# Generated by Django 3.2.17 on 2023-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtemplate',
            name='vendor',
            field=models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='ttptemplate',
            name='vendor',
            field=models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商'),
        ),
    ]
