version: "3.2"

networks:
  docker_netaxe:
    external: true

volumes:
  grafana-data:
    external: true

services:
  grafana:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/grafana:11.1.2
    container_name: grafana
    restart: always
    privileged: true
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_AUTH_JWT_ENABLED: true
      GF_AUTH_JWT_URL_LOGIN: true
      GF_AUTH_JWT_HEADER_NAME: X-AUTH-TOKEN
      GF_AUTH_JWT_KEY_FILE: /etc/grafana/public-key.pem
      GF_AUTH_JWT_EMAIL_CLAIM: sub
      GF_AUTH_JWT_USERNAME_CLAIM: user
      GF_AUTH_JWT_AUTO_SIGN_UP: true
      GF_AUTH_JWT_ALLOW_ASSIGN_GRAFANA_ADMIN: true

    volumes:
      - ./public-key.pem:/etc/grafana/public-key.pem
      - grafana-data:/var/lib/grafana
      # - ./grafana.ini:/usr/share/grafana/conf/defaults.ini
      - ../neteye-compose/provisioning/datasources/prometheus-datasource:/etc/grafana/provisioning/datasources
      - ../neteye-compose/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../neteye-compose/dashboards/victoriametrics-cluster.json:/var/lib/grafana/dashboards/vm.json
      - ../neteye-compose/dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ../neteye-compose/dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
      - ../neteye-compose/dashboards/network.json:/var/lib/grafana/dashboards/network.json
    ports:
      - 3000:3000
    networks:
      - docker_netaxe

