version: "3.2"
networks:
  docker_netaxe:
    external: true
    
services:
  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/nacos-server:2.4.0
    # image: dockerpull.com/nacos/nacos-server
    container_name: nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=NACOS_KEY
      - NACOS_AUTH_IDENTITY_VALUE=NACOS_KEY
      - NACOS_AUTH_TOKEN=NACOS_KEY

      # - NACOS_AUTH_IDENTITY_KEY=pgRb2c4ANvhIA14Z
      # - NACOS_AUTH_IDENTITY_VALUE=pgRb2c4ANvhIA14Z
      # - NACOS_AUTH_TOKEN=NStQdHM3WCU3RVYlMjRZdG04aUolMkM3JTJDQnhyUCU1RXFMJTIxaiUyOCUyM1JZ
#      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql-server
#      - MYSQL_SERVICE_PORT=3306
#      - MYSQL_SERVICE_DB_NAME=nacos
#      - MYSQL_SERVICE_USER=root
#      - MYSQL_SERVICE_PASSWORD=root_devnet@2022
      #模式为单体模式
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - docker_netaxe