version: "3.2"
networks:
  docker_netaxe:
    external: true
    
services:
  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/nacos-server:2.4.0
    # image: dockerpull.com/nacos/nacos-server
    container_name: nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_AUTH_ENABLE=true  # 启用认证
      - NACOS_AUTH_USERNAME=admin  # 设置强用户名
      - NACOS_AUTH_PASSWORD=NACOS_KEY  # 设置强密码
      - NACOS_AUTH_IDENTITY_KEY=NACOS_KEY
      - NACOS_AUTH_IDENTITY_VALUE=NACOS_KEY
      - NACOS_AUTH_TOKEN=NACOS_KEY
      #模式为单体模式
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - docker_netaxe