{
 "title": "网络设备监控",
 "description": "Prometheus数据源，通过SNMP Exporter采集交换机数据做监控",
 "tags": [ "VictoriaMetrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "region", "label": "区域", "query": { "query": "label_values(sysName,region)" } },
   {
    "name": "role",
    "label": "角色",
    "query": {
     "query": "label_values(sysName{region=~\"$region\"},role)"
    }
   },
   {
    "name": "brand",
    "label": "厂商",
    "query": {
     "query": "label_values(sysName{role=~\"$role\", region=~\"$region\"},brand)"
    }
   },
   {
    "name": "device_ip_name",
    "label": "设备",
    "query": {
     "query": "query_result(label_join(sysName{region=~\"$region\", role=~\"$role\", brand=~\"$brand\"}, \"ipname\", \", \", \"instance\", \"sysName\"))"
    }
   },
   { "name": "device_ip", "label": "设备IP", "query": "${device_ip_name}" },
   {
    "name": "interface",
    "label": "接口",
    "query": {
     "query": "query_result(ifHCInOctets{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "设备启动（天）",
   "type": "stat",
   "description": "当前设备运行多长时间（中间无重启或关机）",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmpEngineTime{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} / 86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "sysUpTime{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} / 100/ 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "0 <hh3cEntityExtCpuUsage{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "0 <hwEntityCpuUsage{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "sysCPU{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "CPU1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "CPU2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "0 <hh3cEntityExtMemUsage{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "0 <hwEntityMemUsage{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "sysMemRatio{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "memused{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}/memtotal{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} *100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "skmemused{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}/skmemtotal{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "电源状态",
   "type": "stat",
   "description": "当前电源状态信息",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDevMPowerStatus{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "电源 {{hh3cDevMPowerNum}}"
    },
    {
     "expr": "hwEntityPwrState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "电源 {{hwEntityPwrDesc}}"
    },
    {
     "expr": "myPowerState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "电源 {{myPowerStateDeviceIndex}}{{myPowerStateIndex}}"
    },
    {
     "expr": "power1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "电源 {{myPowerStateDeviceIndex}}{{myPowerStateIndex}}"
    },
    {
     "expr": "power2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "电源 {{myPowerStateDeviceIndex}}{{myPowerStateIndex}}"
    },
    {
     "expr": "mellanoxpwr{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\", mellanoxlName=\"Power Supply\",}/3",
     "legendFormat": "{{mellanoxlName}}"
    },
    {
     "expr": "hillstonePowerState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} +1",
     "legendFormat": "{{ hillstonePowerDescr}}"
    }
   ]
  },
  {
   "title": "风扇状态",
   "type": "stat",
   "description": "当前风扇状态信息",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hh3cDevMFanStatus{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{hh3cDevMFanNum}}"
    },
    {
     "expr": "hwEntityFanState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{hwEntityFanSn}}"
    },
    {
     "expr": "myFanState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk1fan1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk1fan2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk1fan3{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk1fan4{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk2fan4{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk2fan3{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk2fan2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "sk2fan1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
     "legendFormat": "风扇 {{myFanStateDeviceIndex}}{{myFanStateIndex}}"
    },
    {
     "expr": "mellanoxfan{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", mellanoxlName=\"Fan Sensor\",instance=~\"$device_ip\"}",
     "legendFormat": "{{mellanoxlName}}"
    },
    {
     "expr": "(hillstoneFanState{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}+1) < 5",
     "legendFormat": "{{hillstoneFanDescr}} 编号 {{hillstoneFanIndex}}"
    }
   ]
  },
  {
   "title": "设备温度",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "0 <hh3cEntityExtTemperature{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} < 65535",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "0 <hwEntityTemperature{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} < 65535",
     "legendFormat": "{{entPhysicalName}}"
    },
    {
     "expr": "hillstoneTemperatureValue{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{hillstoneTemperatureDescr}}"
    },
    {
     "expr": "ruijieTemperature{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sk1temp1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sk1temp2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sk2temp1{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sk2temp2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sk2temp2{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"} ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "mellanoxtemp{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", mellanoxlName=\"Temperature Sensor\",instance=~\"$device_ip\"} /10",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "接口发送/接收流量",
   "type": "timeseries",
   "description": "指定接口流量",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]) *8",
     "legendFormat": "{{ifName}}  ({{ifAlias}}) 发送"
    },
    {
     "expr": "irate(ifHCInOctets{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]) *8",
     "legendFormat": "{{ifName}}  ({{ifAlias}}) 接收"
    }
   ]
  },
  {
   "title": "【接口错包】+【缓存丢包】",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ceil(increase(ifInErrors{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} Errors 错包接收"
    },
    {
     "expr": "ceil(increase(ifOutErrors{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} Errors 错包发送"
    },
    {
     "expr": "ceil(increase(ifInDiscards{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} Discards 接收"
    },
    {
     "expr": "ceil(increase(ifOutDiscards{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} Discards 发送"
    },
    {
     "expr": "ceil(increase(hh3cifPktBufInDrop{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} 缓存丢包进方向"
    },
    {
     "expr": "ceil(increase(hh3cifPktBufEgDrop{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{ifName}} 缓存丢包出方向"
    }
   ]
  },
  { "title": "接口信息总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "发送（当前-Top10）",
   "type": "bargauge",
   "description": "当前交换机接口流量排序前十",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, irate(ifHCOutOctets{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}[$__rate_interval]) *8 )",
     "legendFormat": "{{ifName}}        "
    }
   ]
  },
  {
   "title": "发送（当前-Top10）",
   "type": "bargauge",
   "description": "当前交换机接口流量排序前十",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, irate(ifHCOutOctets{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}[$__rate_interval]) *8 )",
     "legendFormat": "{{ifName}}        "
    }
   ]
  },
  {
   "title": "接口信息汇总：总数【$total】",
   "type": "table",
   "description": "设备接口信息",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "ifOperStatus{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP邻居监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "BGP邻居信息",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "bgppeerstate{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(localas)  localas * on(instance) group_left(localident) localident * on(instance) group_left(sysName) sysName",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "LLDP邻居监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "LLDP信息",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "lldpLocPortIdSubtype{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\"} * on(instance) group_left(sysName) sysName",
     "legendFormat": "__auto"
    },
    {
     "expr": "lldpRemPortIdSubtype{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "光模块监控（华三）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "光模块监控",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "hh3cTransceiverChannelCurRXPower{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverChannelCurTXPower{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "10 * log10(hh3cTransceiverRcvPwrHiWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 10000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "10 * log10(hh3cTransceiverRcvPwrLoWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 10000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "10 * log10(hh3cTransceiverPwrOutHiWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 10000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "10 * log10(hh3cTransceiverPwrOutLoWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 10000)",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverTemperature{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "光模块监控（华为）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "光模块监控",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "hh3cTransceiverChannelCurRXPower{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverChannelCurTXPower{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} ",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverRcvPwrHiWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverRcvPwrLoWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverPwrOutHiWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverPwrOutLoWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 100",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverTemperature{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "hh3cTransceiverTempHiWarn{instance=~\"$device_ip\", brand=~\"$brand\", role=~\"$role\", region=~\"$region\"} / 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "STP根桥监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "STP根桥监控",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "hh3cdot1sMstiDesignedRoot{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\"} or hwMstpiDesignedRoot{region=~\"$region\", role=~\"$role\", instance=~\"$device_ip\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "华为华三防火墙会话",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "并发会话",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(hh3cSessionStatCount{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"})",
       "legendFormat": "并发会话"
      },
      {
       "expr": "hwSecCurrSessNum{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
       "legendFormat": "{{instance}} 并发会话"
      },
      {
       "expr": "sysCurSession{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
       "legendFormat": "{{instance}} 并发会话"
      }
     ]
    },
    {
     "title": "新建会话",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "sum(hh3cSessionStatCreateRate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"})",
       "legendFormat": "新建会话"
      },
      {
       "expr": "hwSecConSessNum{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
       "legendFormat": "{{instance}} 新建会话"
      },
      {
       "expr": "sysRampupRate{region=~\"$region\", role=~\"$role\", brand=~\"$brand\", instance=~\"$device_ip\"}",
       "legendFormat": "{{instance}} 新建会话"
      }
     ]
    }
   ]
  }
 ]
}