version: "3.2"
networks:
  docker_netaxe:
    external: true

services:
  msggateway-backend:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/msggateway:1.0
    container_name: msggateway-backend
    restart: always
    command: uvicorn controller:app --proxy-headers --timeout-keep-alive 10 --workers 10 --host 0.0.0.0 --port 8000 --log-config config/log-config.yml
    ports:
      - "31101:8000"
    volumes:
      - ./config.json:/app/config/config.json
      - ./logs:/app/logs
    networks:
      - docker_netaxe

  msggateway-nacos:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/msggateway:1.0
    container_name: msggateway-nacos
    restart: always
    command: python3 worker.py nacos
    volumes:
      - ./config.json:/app/config/config.json
      - ./logs:/app/logs
    networks:
      - docker_netaxe


  msggateway-worker:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/msggateway:1.0
    container_name: msggateway-worker
    restart: always
    command: python3 worker.py default
    volumes:
      - ./config.json:/app/config/config.json
      - ./logs:/app/logs
    networks:
      - docker_netaxe

  msggateway-web:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/msggateway-web:1.0
    container_name: msggateway-web
    ports:
      - "32201:80"
    networks:
      - docker_netaxe
    restart: always