# Generated by Django 3.2.17 on 2023-03-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('Huawei', 'Huawei'), ('Cisco', 'Cisco')], default='H3C', max_length=50, verbose_name='厂商')),
                ('category', models.CharField(choices=[('交换机', '交换机'), ('防火墙', '防火墙'), ('路由器', '路由器')], default='交换机', max_length=50, verbose_name='类型')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='采集方案')),
                ('commands', models.TextField(blank=True, default='[]', verbose_name='下发命令')),
                ('netconf_method', models.TextField(blank=True, default='[]', verbose_name='方法列表')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('netconf_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Netconf连接类')),
            ],
            options={
                'verbose_name': '设备数据采集方案',
                'verbose_name_plural': '设备数据采集方案表',
                'db_table': 'device_collection_plan',
                'unique_together': {('name', 'vendor')},
            },
        ),
    ]
