version: '3.8'
services:
  rabbitmq:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/rabbitmq:3.8-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - "32672:15672"
      - "31672:5672"
    volumes:
      - ./data1:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    environment:
      - RABBITMQ_DEFAULT_USER=adminnetaxe
      - RABBITMQ_DEFAULT_PASS=RABBITMQ_PASSWORD
      - STOMP_DEFAULT_USER=adminnetaxe
      - STOMP_DEFAULT_PASS=RABBITMQ_PASSWORD
      - RABBITMQ_DEFAULT_VHOST=netaxe
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - docker_netaxe

networks:
  docker_netaxe:
    external: true


# docker network create docker_netaxe
# rabbitmqctl set_permissions -p /  adminnetaxe ".*" ".*" ".*"
