# Generated by Django 3.2 on 2022-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgBu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='业务名称')),
            ],
            options={
                'verbose_name': '业务表',
                'verbose_name_plural': '业务表',
                'db_table': 'bgbu',
            },
        ),
        migrations.AddIndex(
            model_name='bgbu',
            index=models.Index(fields=['name'], name='bgbu_name_7454a1_idx'),
        ),
    ]
