# Generated by Django 3.2.17 on 2023-02-21 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
