version: "3.2"
networks:
  docker_netaxe:
    external: true
    
services:
  web_main:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/web_main:2.0
    container_name: web_main
    restart: always
    ports:
      - "9980:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker_netaxe