# Generated by Django 3.2 on 2022-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=50, verbose_name='厂商')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='采集方案')),
                ('commands', models.TextField(blank=True, default='[]', verbose_name='下发命令')),
                ('netconf_method', models.TextField(blank=True, default='[]', verbose_name='方法列表')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('netconf_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Netconf连接类')),
            ],
            options={
                'verbose_name': '设备数据采集方案',
                'verbose_name_plural': '设备数据采集方案表',
                'db_table': 'device_collection_plan',
                'unique_together': {('name', 'vendor')},
            },
        ),
    ]
